config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :usuarios, as: :users,only: [:show,:update]
  resources :friendships, only: [:create,:update,:index]

  devise_for :users, controllers:{
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"

  #Para usuarios autenticados:
    authenticated :user do
        root 'main#home'
    end
  #Para usuarios no autenticados:
    unauthenticated :user do
        root 'main#unregistered'
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  ActionCable.server.config.disable_request_forgery_protection = true
end

app/views/partials/_nav.haml
%header.mdl-layout__header.mdl-layout__header--scroll
  .mdl-layout__header-row.white-text
    %span.mdl-layout-title=link_to "Cyberdreams",root_path,class:"white-text",style:"text-decoration:none;"
    .mdl-layout-spacer
    %nav.mdl-navigation
      -if user_signed_in?
        =link_to "My connections", friendships_path, class:"white-text right-space"
        =link_to current_user.username, current_user, class:"white-text right-space"
        =link_to "Sign out", destroy_user_session_path, method: :delete, class:"white-text"

.mdl-layout__drawer
  %span.mdl-layout-title Cyberdreams
  %nav.mdl-navigation
    %a.mdl-navigation__link{:href => ""} Link
    %a.mdl-navigation__link{:href => ""} Link
    %a.mdl-navigation__link{:href => ""} Link
    %a.mdl-navigation__link{:href => ""} Link